# SPDX-License-Identifier: GPL-2.0-only

"""
BUILD.bazel for @bionic.
"""

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "libc/kernel/tools/clean_header_deps",
    srcs = [
        "libc/kernel/tools/cpp.py",
        "libc/kernel/tools/defaults.py",
        "libc/kernel/tools/kernel.py",
        "libc/kernel/tools/utils.py",
    ],
)

filegroup(
    name = "libc/kernel/tools/clean_header_py",
    srcs = [
        "libc/kernel/tools/clean_header.py",
    ],
)
