# SPDX-License-Identifier: GPL-2.0-only

"""
Defines kernel targets which are aliases of real kernel targets from the kernel
package selected by --kernel_package=<package>.
"""

load("//private/devices/google/common/kleaf:kernel_selection.bzl", "kernel_package", "kernel_selection")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

_KERNEL_TARGETS = [
    # keep sorted
    "aarch64_additional_kmi_symbol_lists",
    "all_headers_aarch64",
    "include/uapi/drm/drm_fourcc.h",
    "include/uapi/sound/asound.h",
    "include/uapi/sound/compress_offload.h",
    "include/uapi/sound/compress_params.h",
    "kernel_aarch64",
    "kernel_aarch64_config",
    "kernel_aarch64_gki_artifacts",
    "kernel_aarch64_headers",
    "kernel_aarch64_images",
    "kernel_aarch64_modules",
    "kernel_aarch64_sources",
    "set_kernel_dir_build_config",
]

kernel_selection(
    name = "kernel_package",
    default = "ack",
    packages = [
        kernel_package(
            name = "ack",
            aliases = ["@//aosp"],
            package = "//common/ack",
        ),
        kernel_package(
            name = "gki",
            aliases = ["@//aosp-with-prebuilts"],
            package = "//common/gki",
            prebuilt_repos = {
                "kernel_aarch64": "download_or_build",
                "kernel_aarch64_16k": "download_or_build",
            },
        ),
        kernel_package(
            name = "staging",
            aliases = ["@//aosp-staging"],
            package = "//common/staging",
        ),
        kernel_package(
            name = "bringup",
            aliases = ["@//aosp-bringup"],
            package = "//common/bringup",
        ),
    ],
    targets = _KERNEL_TARGETS,
)
