# bcmdhd
#
# Copyright (C) 2026, Broadcom.
#
#      Unless you and Broadcom execute a separate written software license
# agreement governing use of this software, this software is licensed to you
# under the terms of the GNU General Public License version 2 (the "GPL"),
# available at http://www.broadcom.com/licenses/GPLv2.php, with the
# following added to such license:
#
#      As a special exception, the copyright holders of this software give you
# permission to link this software with independent modules, and to copy and
# distribute the resulting executable under terms of your choice, provided that
# you also meet, for each linked independent module, the terms and conditions of
# the license of that module.  An independent module is a module which is not
# derived from this software.  The special exception does not apply to any
# modifications of the software.
#
#
# <<Broadcom-WL-IPTag/Dual:>>
#

# include main kernel build env for BCMDHD if exists
-include $(BCMDHD_ROOT)/BCMDHD.Kbuild
ifeq ($(BCMDHD),)
  GG_REF_PLATFORM=1
endif

# Path to the module source, KERNEL_SRC is defined for out-of-tree Kbuild
# and BCMDHD_ROOT is passed as KBUILD_OPTIONS for out-of-tree Makefile
ifeq ($(KERNEL_SRC),)
  ifeq ($(srctree),.)
    BCMDHD_ROOT=$(src)
  else
    BCMDHD_ROOT=$(srctree)/$(src)
  endif
endif

# For pixel build, unset SOC related configs which are defined in DHD
ifneq ($(filter y, $(CONFIG_SOC_GOOGLE) $(CONFIG_SYNAPTICS_SOC)),)
  # Find configs in DHD code with prefix "CONFIG_ARCH_"
  ARCH_CONFIGS := $(shell grep -rEoh "CONFIG_ARCH_([0-9]|[A-Z]|_)+" $(BCMDHD_ROOT)/* | sort | uniq)

  # Unset these CONFIG_ARCH_* configs if it is defined in kernel layer
  $(foreach var, $(ARCH_CONFIGS), $(eval $(var) :=))
endif

ifneq ($(CONFIG_SOC_GOOGLE),)
	DHDCFLAGS += -DBCMDHD=$(BCMDHD)
endif

DHDCFLAGS += \
  -Wall \
  -Werror \
  -Wno-parentheses-equality \
  -Wno-macro-redefined \
  -Wstrict-prototypes

DHDCFLAGS += --std=gnu17

##########################
# driver type
# m: module type driver
# y: built-in type driver
##########################
DRIVER_TYPE ?= m

# Add chip specific suffix to the output on customer release
ifeq ($(BCMDHD),4388)
  BCM_WLAN_CHIP_SUFFIX = 4389
else ifeq ($(BCMDHD),4398)
  BCM_WLAN_CHIP_SUFFIX = 4398
else ifeq ($(BCMDHD),4390)
  BCM_WLAN_CHIP_SUFFIX = 4390
else ifeq ($(BCMDHD),4383)
  BCM_WLAN_CHIP_SUFFIX = 4383
endif

DHDCFLAGS += -DDHD_COMPILED=\"$(BCMDHD_ROOT)\"
DHDCFLAGS += -I$(BCMDHD_ROOT)/include/ -I$(BCMDHD_ROOT)/
DHDCFLAGS += -Wno-date-time
ifeq ($(KERNEL_SRC),)
  KBUILD_CFLAGS += -I$(LINUXDIR)/include -I$(CURDIR)
endif

DHDOFILES := \
  aiutils.o \
  bcmbloom.o \
  bcmcapext.o\
  bcmevent.o \
  bcmstdlib_s.o \
  bcmutils.o \
  bcmwifi_channels.o \
  bcmwifi_channels_shared.o \
  bcmxtlv.o \
  bcm_app_utils.o \
  dhd_cfg80211.o \
  dhd_common.o \
  dhd_custom_gpio.o \
  dhd_dbg_ring.o \
  dhd_debug.o \
  dhd_debug_linux.o \
  dhd_ip.o \
  dhd_linux.o \
  dhd_linux_exportfs.o \
  dhd_linux_pktdump.o \
  dhd_linux_platdev.o \
  dhd_linux_rx.o \
  dhd_linux_sched.o \
  dhd_linux_tx.o \
  dhd_linux_wq.o \
  dhd_log_dump.o \
  dhd_mschdbg.o \
  dhd_pno.o \
  dhd_rtt.o \
  frag.o \
  hndpmu_dhd.o \
  hnd_pktpool.o \
  hnd_pktq.o \
  linuxerrmap.o \
  linux_osl.o \
  linux_pkt.o \
  siutils.o \
  siutils_host.o \
  wldev_common.o \
  wl_android.o \
  wl_cfg80211.o \
  wl_cfgnan.o \
  wl_cfgp2p.o \
  wl_cfgscan.o \
  wl_cfgvif.o \
  wl_cfgvendor.o \
  wl_cfg_btcoex.o \
  wl_linux_mon.o \
  wl_cfgtwt.o

# This file will be here only for internal builds and sets flags which may
# affect subsequent behavior. See extended comment within it for details.
_dhd_lx_mk_dir := $(dir $(lastword $(MAKEFILE_LIST)))
-include $(_dhd_lx_mk_dir)bcminternal-android.mk

DHDCFLAGS += $(BCMINTERNAL_DFLAGS)
DHDOFILES += $(BCMINTERNAL_DHDOFILES)

# extra Source files
DHDOFILES += dhd_cfg_dscp_policy.o
DHDOFILES += nciutils.o nciutils_host.o hal_nci_cmn.o

# if FW_SIGNATURE is defined add fwpkg_utils.c
DHDOFILES += fwpkg_utils.o

DHDOFILES += wl_roam.o
DHDOFILES += wb_regon_coordinator.o
DHDOFILES += dhd_pktlog.o
DHDOFILES += dhd_statlog.o

ifneq ($(CONFIG_SOC_GOOGLE),)
  ifeq ($(BCMDHD),4390)
    DHDOFILES += dhd_custom_google_4390.o
  else ifeq ($(BCMDHD),4383)
    DHDOFILES += dhd_custom_google_4383.o
  else
    DHDOFILES += dhd_custom_google_4398.o
  endif
else ifneq ($(CONFIG_ARCH_HISI),)
  DHDOFILES += dhd_custom_hikey.o
else ifneq ($(CONFIG_ARCH_BRCMSTB),)
  DHDOFILES += dhd_custom_stb.o
else ifneq ($(CONFIG_ARCH_MESON),)
  DHDOFILES += dhd_custom_meson.o
else ifneq ($(CONFIG_SYNAPTICS_SOC),)
  DHDOFILES += dhd_custom_astra.o
endif

DHDOFILES += dhd_custom_memprealloc.o

ifneq ($(CONFIG_BCMDHD_SDIO),)
  DHDOFILES += bcmsdh.o bcmsdh_linux.o bcmsdh_sdmmc.o bcmsdh_sdmmc_linux.o
  DHDOFILES += dhd_cdc.o dhd_wlfc.o dhd_sdio.o
endif

DHDOFILES += dhd_pcie.o dhd_pcie_dumps.o dhd_pcie_linux.o dhd_msgbuf.o dhd_flowring.o
DHDOFILES += pcie_core_host.o
DHDOFILES += dhd_linux_lb.o
DHDOFILES += dhd_event_log_filter.o
DHDOFILES += dhd_custom_cis.o
DHDOFILES += dhd_pcie_sssr_dump.o
DHDOFILES += wl_cfg_cellavoid.o

bcmdhd$(BCM_WLAN_CHIP_SUFFIX)-objs := $(sort $(DHDOFILES))
obj-$(DRIVER_TYPE)   += bcmdhd$(BCM_WLAN_CHIP_SUFFIX).o
ccflags-y := $(KBUILD_CFLAGS)
ccflags-y += $(DHDCFLAGS)
# Use the full path to dhd_defines.h
ccflags-y += -include $(BCMDHD_ROOT)/dhd_defines.h

# For in-tree model, define make rules here (KERNEL_SRC will be NULL)
ifeq ($(KERNEL_SRC),)
all:
	@$(strip @set -x; $(MAKE) --no-print-directory -C $(KDIR) \
	  SUBDIRS=$(CURDIR) modules $(KBUILD_OPTIONS))

modules_install:
	@$(strip @$(MAKE) --no-print-directory -C $(KDIR) \
	  SUBDIRS=$(CURDIR) modules_install)

clean:
	$(RM) -r *.o *.ko *.mod.c *~ .*.cmd *.o.cmd .*.o.cmd \
	  Module.symvers modules.order .tmp_versions modules.builtin
endif

# This comment block must stay at the bottom of the file.
# Local Variables:
# mode: GNUmakefile
# fill-column: 80
# End:
#
# vim: filetype=make sw=2 tw=80 cc=+1 noet
