# SPDX-License-Identifier: GPL-2.0
#
# This file should be included by external modules that need to link to this
# project.

subdir-ccflags-y += -I$(ROOT_DIR)/private/google-modules/soc/gs/include
subdir-ccflags-y += -I$(ROOT_DIR)/private/google-modules/soc/gs/include/uapi

EXTRA_SYMBOLS += $(wildcard $(COMMON_OUT_DIR)/private/google-modules/soc/gs/Module.symvers)
