#!/bin/bash -e
# SPDX-License-Identifier: GPL-2.0-only

source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/envsetup.sh"

OUTPUT_ROOT=

function init() {
  OUTPUT_ROOT="${WORKSPACE_DIR}/out"

  # Kleaf's bazel wrapper only recognizes startup options in --<key>=<value> format.
  # --<key> <value> can not be recognized. Let's align with it.
  while (( $# > 0 )); do
    case "$1" in
      --output_root=*)
        OUTPUT_ROOT="$(realpath -s "${1#--output_root=}")"
        ;;
      -*)
        # Other startup options.
        ;;
      *)
        # Assume the first option not starting with `-` is the command.
        break
        ;;
    esac
    shift
  done

  readonly OUTPUT_ROOT
}

function setup_cog_workspace() {
  if [[ ! "${WORKSPACE_DIR}" =~ ^/google/cog/ ]]; then
    return 0
  fi

  if [[ ! "${OUTPUT_ROOT}" =~ ^"${WORKSPACE_DIR}/" ]]; then
    return 0
  fi

  if [[ -d "${OUTPUT_ROOT}" && ! -L "${OUTPUT_ROOT}" ]]; then
    echo "Detected existing output directory in the Cog workspace which is not supported. Removing."
    rm -rf "${OUTPUT_ROOT}"
  fi

  local -r cog_workspace_name="$(basename "$(dirname "${WORKSPACE_DIR}")")"
  local -r link_destination_dir="${HOME}/.cache/cog/${cog_workspace_name}"

  local link_destination="${OUTPUT_ROOT/"${WORKSPACE_DIR}"/"${link_destination_dir}"}"
  if [[ -L "${OUTPUT_ROOT}" ]]; then
    # Respect the existing link destination.
    link_destination="$(readlink -m "${OUTPUT_ROOT}")"
  fi
  readonly link_destination

  mkdir -p "${link_destination}"

  if [[ -L "${OUTPUT_ROOT}" ]]; then
    return 0
  fi

  echo "Creating symlink: ${OUTPUT_ROOT} -> ${link_destination}"
  ln -snf "${link_destination}" "${OUTPUT_ROOT}"
}

function import_device_bazelrc () {
  local search_dir="${WORKSPACE_DIR}/private/devices"
  local gen_device_bazelrc="${OUTPUT_ROOT}/bazel/bazelrc/device.bazelrc"

  local -a device_bazelrc_list
  readarray -t device_bazelrc_list < <(find "${search_dir}" -name device.bazelrc)

  mkdir -p "$(dirname "${gen_device_bazelrc}")"
  echo "# This file is auto-generated by tools/bazel." > "${gen_device_bazelrc}"

  local rc
  for rc in "${device_bazelrc_list[@]}"; do
    echo "import \"${rc/"${WORKSPACE_DIR}"/"%workspace%"}\"" >> "${gen_device_bazelrc}"
  done
  ln -snf "${gen_device_bazelrc}" "${WORKSPACE_DIR}/device.bazelrc"
}

function main() {
  init "$@"
  setup_cog_workspace
  import_device_bazelrc
  exec "${WORKSPACE_DIR}/build/kernel/kleaf/bazel.sh" "$@"
}

main "$@"
