# SPDX-License-Identifier: GPL-2.0-or-later

load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "ddk_module")

package(
    default_visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

_PANEL_LOCAL_DEFINES = [
    "DYNAMIC_DEBUG_MODULE",
] + select({
    "//private/devices/google/common:factory_build": ["PANEL_FACTORY_BUILD"],
    "//conditions:default": [],
})

ddk_headers(
    name = "common_headers",
    hdrs = [
        "//common:all_headers_aarch64",
        "//private/google-modules/display/common:ddk_headers",
    ],
    visibility = ["//visibility:private"],
)

# Note: please add additional drivers as separate ddk modules

ddk_module(
    name = "panel-gs-staea",
    srcs = [
        "panel-gs-staea.c",
    ],
    out = "panel-gs-staea.ko",
    kernel_build = "//private/devices/google/common:kernel",
    local_defines = _PANEL_LOCAL_DEFINES,
    deps = [
        ":common_headers",
        "//private/google-modules/display/common/gs_panel",
    ],
)
