# SPDX-License-Identifier: GPL-2.0-or-later

load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

filegroup(
    name = "sscoredump.kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

kernel_module(
    name = "sscoredump",
    srcs = glob([
        "*.c",
    ]) + [
        "Makefile",
        "//private/google-modules/soc/gs:gs_soc_headers",
    ],
    outs = [
        "sscoredump_sample_test.ko",
        "sscoredump_test.ko",
    ],
    kernel_build = "//private/devices/google/common:kernel",
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
    deps = [
        "//private/google-modules/soc/gs:gs_soc_module",
    ],
)
