# SPDX-License-Identifier: GPL-2.0-only

load(":copy_files_test.bzl", "copy_files_test")
load(":create_file_test.bzl", "create_file_test")
load(":merged_uapi_headers_test.bzl", "merged_uapi_headers_test")

copy_files_test(name = "copy_files_test")

create_file_test(name = "create_file_test")

merged_uapi_headers_test(name = "merged_uapi_headers_test")

test_suite(
    name = "tests",
)
