# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(ROOT_DIR)/private/google-modules/display
ccflags-y += -I$(ROOT_DIR)/private/google-modules/display/samsung/include/uapi
ccflags-y += -I$(ROOT_DIR)/private/google-modules/touch/common
ccflags-y += -I$(ROOT_DIR)/private/google-modules/touch/common/include

# FTM5 support
obj-$(CONFIG_TOUCHSCREEN_FST2)	+= fst2.o
fst2-objs = fts.o fts_proc.o
fst2-objs += \
	fts_lib/fts_flash.o fts_lib/fts_io.o fts_lib/fts_test.o

