name: Build Kernel
run-name: Build ${{ inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Device target"
        required: true
        type: choice
        options:
          - gs201
          - zuma
          - zumapro
          - all

jobs:
  prepare:
    runs-on: ubuntu-24.04

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Set build matrix
        id: set-matrix
        run: |
          if [ "${{ inputs.target }}" = "all" ]; then
            echo 'matrix=["gs201","zuma","zumapro"]' >> "$GITHUB_OUTPUT"
          else
            echo 'matrix=["${{ inputs.target }}"]' >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: prepare

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            cpio \
            zip \
            unzip \
            curl \
            git \
            patch

      - name: Configure Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Make scripts executable
        run: |
          chmod +x patch_sultan.sh
          chmod +x build_sultan.sh

      - name: Patch kernel
        run: |
          ./patch_sultan.sh ${{ matrix.target }}

      - name: Build kernel
        run: |
          ./build_sultan.sh ${{ matrix.target }}

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: SULTAN17_KSU_${{ matrix.target }}
          path: AnyKernel/
          compression-level: 0
