name: Build Kernel
run-name: Build ${{ inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Device target"
        required: true
        type: choice
        options:
          - gs201
          - zuma
          - zumapro
          - all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(
          inputs.target == 'all'
            && '["gs201","zuma","zumapro"]'
            || format('["{0}"]', inputs.target)
        ) }}

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            cpio \
            zip \
            unzip \
            curl \
            git \
            patch

      - name: Configure Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Make scripts executable
        run: |
          chmod +x patch_sultan.sh
          chmod +x build.sh

      - name: Patch kernel
        run: |
          ./patch_sultan.sh ${{ matrix.target }}

      - name: Build kernel
        run: |
          ./build.sh ${{ matrix.target }}

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: SULTAN17_KSU_${{ matrix.target }}
          path: dist/*.zip
