name: Build Kernel

on:
  push:
    branches:
      - sultan-17

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Show environment
        run: |
          uname -a
          gcc --version
